---
collections:
  - name: devsec.hardening
    version: 10.6.0
  - name: prometheus.prometheus
    version: 0.30.0
roles:
  - src: hafu.systemd_timesyncd
  - src: Frzk.nftables
  - src: stuvusit.systemd-journald
  - name: robertdebock.users
    version: 6.1.8
